---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boids-simulation-config
  namespace: boids-simu
data:
  MQTT_BROKER: tcp://mosquitto-svc.mqtt-broker.svc.cluster.local:1883
  MQTT_TOPIC: boids/positions